# -*- coding: utf-8 -*-
"""
Created on Thu Aug 14 17:22:31 2025

@author: Evan Shapiro
"""

# -*- coding: utf-8 -*-
"""
Created on Fri Jan 19 10:53:31 2024

@author: shap293
"""
#Make sure that the working directory is the PNNL_Internship directory
import os 
import empymod
import numpy as np
os.chdir('D:\\PNNL\\')
module_dir = os.path.abspath('./Testing/')
sys.path.insert(0, module_dir)
from Testing_Function_Module import *

def keras_prep(X, n_inputs, n_features):
    
   
    # if X.ndim ==1:
    X_f = X.reshape((1, 11, 1))
    # else:
    #     dim_0 = X.shape[0]
    #     X_f = X.reshape((dim_0, 11, 1))
    return X_f

def sim_empymod_data( rho_data, depth, verb, ab, freq, xdirect,
                      fx, fy,  heights, save_data = False):
     
     n_freq = freq.shape[0]
     n_rec = fx.shape[0]
     
     # dim_0 = s_rmd_rho.shape[1]
     
     fEMBG_arr = np.zeros( 2*n_freq*n_rec )
     
     # for i in range( 0, dim_0):
         
     t_h = heights[0]
     r_h = t_h
     inpdat = {'src': [0, 0, t_h], 'rec': [fx, fy, r_h], 'depth': depth,
             'freqtime': freq, 'ab': ab, 'xdirect': xdirect,
             'htarg': {'pts_per_dec': -1}, 'verb': verb}
    
     fEMBG = empymod.dipole(**inpdat, res = rho_data)
    
     if n_rec == 1:
         for k in range(0,n_freq):
             fEMBG[k] = 1j*8*np.pi**2*1e-7*freq[k]*fEMBG[k]
            
     if n_rec > 1:
         for k in range(0,n_freq):
             fEMBG[k,:] = 1j*8*np.pi**2*1e-7*freq[k]*fEMBG[k,:]
        
     fEMBG_real = fEMBG.real
     fEMBG_imag = fEMBG.imag
     for k in range(0,n_freq):
         for m in range(0,n_rec):
            #Array structure: 
            #[Amplitude of 1Hz response @ Receiver_1,
            #Amplitude of 1Hz response @ Receiver_2,
            #Amplitude of 1Hz response @ Receiver_3,
            #Amplitude of 10Hz response @ Receiver_1,...]
            if n_rec == 1:
                fEMBG_arr[2*m + 2*n_rec*k] = fEMBG_real[k]
                fEMBG_arr[1+2*m + 2*n_rec*k] = fEMBG_imag[k]
                
            if n_rec > 1:
                fEMBG_arr[ 2*m + 2*n_rec*k] = fEMBG_real[k,m]
                fEMBG_arr[1 + 2*m + 2*n_rec*k] = fEMBG_imag[k,m]     
     return fEMBG_arr
 
def emp_fw_sim(res_data, depth, height):
    
    
    verb = 0
    #Orientation of magnetic field source and receiver.
    #66 means that the magnetic source and receiver are aligned along the z-axis
    ab = 66
    
    #EM-Frequencies Generated by Source 
    freq = np.array([382, 1822, 7970, 35920, 130100]) #adjust function to make frequency an input parameter
    freq_dim = freq.shape[0]    
    fem_dim = 2*freq.shape[0] + 1
    
    xdirect = None
    
    #fx is the array of the position of the receivers along x-axis
    fx = np.array([7.86])
    #fx is the array of the position of the receivers along y-axis
    fy = np.zeros(fx.shape)
    
    # height load height from true frequency data set
    
    fEM_data = sim_empymod_data(res_data, depth, verb, ab, freq, xdirect,
                          fx, fy, height, save_data = False)
    return fEM_data, freq

def pred_fun(net_dict_path, model_path, in_data_path, test_idx, 
                     training, scaler_in_path = []):
    
    data_dict = np.load(net_dict_path)
    
    inputs_n = data_dict['inputs_n']
    features_n = data_dict['features_n']
    Y_l_max = data_dict['Y_l_max']
    Y_l_min = data_dict['Y_l_min']
    off_n = data_dict['off_n']
    freq_n = data_dict['freq_n']
    
    X = np.load(in_data_path)
    if len(test_idx ) == 1:  
        test_idx = test_idx[0]
        X = X[test_idx,:]
        X = X.reshape(1,-1)    
    else:
        X = X[test_idx,:]
    
    
    if scaler_in_path:
        scaler_in = joblib.load(scaler_in_path)
        X = scaler_in.transform(X)
    
        
    X = keras_prep(X, inputs_n, features_n)
    model = tf.keras.models.load_model(model_path)
    Y_p = model(X, training = training)
    
    # print('Time to perform inference with', test_idx.shape[0], 'MC samples = ', et - st  )
    # print('Avg. time per sample = ', (et - st)/test_idx.shape[0] )
    # Y_p = Res_Inv_Trans(Y_p, Y_l_max, Y_l_min)
    Y_p = 10**(Y_p*(Y_l_max - Y_l_min)+Y_l_min)
    Y_p = Y_p.numpy()
    return Y_p

def load_true_data(out_data_path, idx_arr):
    Y = np.load(out_data_path)
    Y_true = Y[idx_arr,:]
    return Y_true



def res_test_plot(data_path, depth_path, plot_idx, title, label_list = [], Y_p = []):
    
    depth = import_depth(depth_path)
    if not Y_p.all():    
        Y_p = np.load(data_path)
        Y_p = Y_p[plot_idx, 1:]
    else:
        Y_p = Y_p[plot_idx, :]
    
    pdepth = np.repeat(np.r_[depth], 2)
    pdepth[:-1] = pdepth[1:]
    pdepth[-1] = 2*depth[-1]
    pres_p = np.repeat(Y_p, 2)
    
    # Create figure
    fig = plt.figure(figsize=(7, 5), facecolor='w')
    fig.subplots_adjust(wspace=.25, hspace=.4)
    
    # Plot Resistivities
    ax1 = plt.subplot(1, 2, 1)
    plt.plot(pres_p, pdepth, 'b', label = 'DL-RMD Database Model')
    plt.xscale('log')
    plt.xlim([0.75*Y_p[1:].min(), 1.5*Y_p[1:].max()])
    # plt.xlim([0.5e-1, 1e2])
    plt.ylim([1.5*depth[-1],-1])
    plt.ylabel('Depth (m)')
    plt.xlabel(r'Resistivity $\rho_h\ (\Omega\,\rm{m})$')
    plt.title(title)
    plt.show
    return

def res_test_plot_2(Y_list, depth_path, plot_idx, title, label_list = [], Y_p = []):
    
    y_true = Y_list[0]
    y_pred = Y_list[1]
    depth = import_depth(depth_path)
    # y_true = Y_true[plot_idx,:]
    # y_pred = Y_pred[plot_idx, :]
    
    pdepth = np.repeat(np.r_[depth], 2)
    pdepth[:-1] = pdepth[1:]
    pdepth[-1] = 2*depth[-1]
    pres_true = np.repeat(y_true, 2)
    pres_pred = np.repeat(y_pred, 2)
    
    # Create figure
    fig = plt.figure(figsize=(7, 5), facecolor='w')
    fig.subplots_adjust(wspace=.25, hspace=.4)
    
    # Plot Resistivities
    # ax1 = plt.subplot(1, 2)
    plt.plot(pres_true, pdepth, 'b', label = 'DL-RMD Database Resistivity Model')
    plt.plot(pres_pred, pdepth, 'g', label = 'CNN Inverted Resistivity Model')
    plt.xscale('log')
    plt.xlim([0.75*y_pred[1:].min(), 1.5*y_pred[1:].max()])
    # plt.xlim([0.5e-1, 1e2])
    plt.ylim([1.5*depth[-1],-1])
    plt.ylabel('Depth (m)')
    plt.xlabel(r'Resistivity $\rho_h\ (\Omega\,\rm{m})$')
    plt.title(title)
    plt.legend()
    plt.show
    return

depth_path = f'./Data/simulated_data/date_10_10_25/depth_data.npy'
depth = import_depth(depth_path)

out_data_path = './Data/experiments/date_10_23_25/noise_05_test/tvt_data/y_test_data.npy'
freq_data_path_1 = './Data/experiments/date_10_23_25/noise_05_test/tvt_data/x_test_ltr_noise.npy'
# freq_data_path_2 = './Data/experiments/date_10_9_25/noise_05_test_ltr/tvt_data/x_val_data.npy'
net_dict_path =   './Data/experiments/date_10_23_25/noise_05_test/model/nn_dict.npz'
model_path = './Data/experiments/date_10_23_25/noise_05_test/model/nn_model.keras'
scaler_in_path = './Data/experiments/date_10_23_25/noise_05_test/tvt_data/scaler_in.pkl'

# out_data_path = './Data/experiments/date_10_9_25/noise_05_test_ltr/tvt_data/y_train_data.npy'
# freq_data_path_1 = './Data/experiments/date_10_9_25/noise_05_test_ltr/tvt_data/x_train_proc.npy'
# freq_data_path_2 = './Data/experiments/date_8_27_25/noise_05_test/tvt_data/x_val_data.npy'
# net_dict_path =   './Data/experiments/date_8_27_25/noise_05_test/model/nn_dict.npz'
# model_path = './Data/experiments/date_8_27_25/noise_05_test/model/nn_model.keras'
# # scaler_in_path = './Data/experiments/date_8_27_25/noise_05_test/model/scaler_in.pkl'
# depth_path = f'./Data/simulated_data/date_10_10_25/depth_data.npy'
# depth = import_depth(depth_path)

# #Set in_data_path to original data path



plot_idx = [0]
training = False

y_pred = pred_fun(net_dict_path, model_path, freq_data_path_1, plot_idx, 
                      training, scaler_in_path)

# y_pred = y_pred.reshape(31)
y_pred_pl = y_pred[0, 1:]
y_true_0 = load_true_data(out_data_path, plot_idx[0])
y_true = y_true_0[1:]

#Label for plotted profiles - Used when plotting predicted test data where truth
# is known.
data_path = f'./Data/simulated_data/rho_data_scaled_01_1_2x.npy'
plot_labels = ['True Model', 'CNN Predicted Model', ]
title_1 = f'True Resistivity Model vs. CNN Inverted Resistivity Model'
pdepth = np.repeat(np.r_[depth], 2)
pdepth[:-1] = pdepth[1:]
pdepth[-1] = 2*depth[-1]
pres_true = np.repeat(y_true, 2)
pres_pred = np.repeat(y_pred_pl, 2)

freq_data = np.load(freq_data_path_2)
height = freq_data[0]
fdem_true = freq_data[plot_idx,1:]

y_pred = y_pred[0,:]
fdem_true, exp_freq = emp_fw_sim(y_true_0, depth, height)
fdem_pred, exp_freq = emp_fw_sim(y_pred, depth, height)



mre = np.round(np.mean(np.abs(fdem_true - fdem_pred)/np.abs(fdem_true)), decimals = 2)
#plot true vs. predicted FDEM values
x = [382, 382, 1822, 1822, 7970, 7970, 35920, 35920, 130100, 130100]
fig, (ax1, ax2) = plt.subplots(1,2, figsize = (13,13))
ax1.plot(pres_true, pdepth, 'b', label = 'DL-RMD Database Resistivity Model')
ax1.plot(pres_pred, pdepth, 'g', label = 'CNN Inverted Resistivity Model')
ax1.set_xscale('log')
ax1.set_xlim([0.75*y_pred[1:].min(), 1.5*y_pred[1:].max()])
# plt.set_xlim([0.5e-1, 1e2])
ax1.set_ylim([1.5*depth[-1],-1])
ax1.set_ylabel('Depth (m)')
ax1.set_xlabel(r'Resistivity $\rho_h\ (\Omega\,\rm{m})$')
ax1.set_title(title_1)
ax1.legend()

mre = np.round(np.mean(np.abs(fdem_true - fdem_pred)/np.abs(fdem_true)), decimals = 2)

ax2.scatter(x,np.abs(fdem_true), color = 'blue', label = 'True FDEM-Data' )
ax2.scatter(x,np.abs(fdem_pred), color = 'green', label = 'CNN Predicted FDEM-Data' )
ax2.set_title(f'Simulated FDEM Data Comparison Mean Abs. Relative Error = {mre} ')
ax2.set_yscale('log')
ax2.set_xlabel('Real & Imaginary Secondary FDEM Component')
ax2.set_ylabel('Secondary FDEM Amplitude')
ax2.legend()

#percent error for fdem data
print(np.mean(np.abs(fdem_true - fdem_pred)/np.abs(fdem_true)))

# axs[1] = plt.legend()
# plt.show