# -*- coding: utf-8 -*-
"""
Created on Tue Aug 15 15:52:40 2023

@author: shap293
"""

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""


# Change the working directory to the PNNL_Internship directory
# This simulation uses Empymod, and simulates data for a z-oriented
# magnetic field dipole.
# For reference, and to understand the model variables
# the documentation for Empymod can be found here. 
# https://empymod.emsig.xyz/en/stable/manual/index.html 
# You need to have Empymod installed in your python environment

import numpy as np
import scipy as sp
import empymod
import time
import os
import sys
import h5py

import random

ran_int = 14
print('ran_int', ran_int)
# Set the random seed to a specific integer value
random.seed(ran_int) 


os.chdir('/Users/evanshapiro/Documents/PhD_Research/geophysical_inversion_project/')
module_dir = os.path.abspath('./Coding/Simulation/')
sys.path.insert(0, module_dir)

from Simulation_Function_Module import *



#Path to set of resistivity profiles from S_RMD_Data
# res_data_path ="./Data/RMD_Data/S_RMD_rho.txt"
res_data_path = './data/rmd_data/S_RMD_rho.txt'
#Path to depth profile - (Absolute Layer Profile)
depth_data_path = './data/cedar_rapids_data/depth_profile.csv'

#Save Paths
#EM Data save path
fEM_save_path = './data/simulated_data/fEM_ppm_data_test.npy'

#resistivity data save path
rho_save_path = f'./data/simulated_data/rho_data_test.npy'

#simulation parameters save path
# sim_dict_path = f'./Data/simulated_data/date_2_13_26/sim_dict_sc_{ran_int}.npy'

# directory = 'D:\\PNNL\\Data\\Validation\\bookpurnong_inversion'
# resolve = h5py.File(os.path.sep.join([directory, "booky_resolve.hdf5"]), "r")
# heights = resolve['src_elevation']

#Scaling Factors
depth_fac = 2
rho_fac = 1

depth = np.loadtxt(depth_data_path, delimiter = ',', encoding='utf-8-sig')
# depth_prof = np.loadtxt(depth_data_path, delimiter = ',', encoding='utf-8-sig')

# s_rmd_thk = np.loadtxt(depth_data_path, delimiter = ',')
s_rmd_rho_in = np.loadtxt(res_data_path, delimiter = ',')
# s_rmd_rho_in = np.loadtxt(res_data_path, delimiter = ',')

air_layer = np.ones(s_rmd_rho_in.shape[1]).reshape(1,-1)*1e14
s_rmd_rho = np.append(air_layer, s_rmd_rho_in[0:29,:], axis = 0)

rho_dim = s_rmd_rho.shape[0]
# depth_dim = rho_dim - 1

# depth = np.empty(depth_dim)
# depth[0] = 0
# for i in range(1,depth_dim ):
#     depth[i] = depth_fac*np.sum(s_rmd_thk[0:i])

verb = 0

# depth = np.r_[0, np.cumsum(s_rmd_thk)]
#Orientation of magnetic field source and receiver.
#66 means that the magnetic moment of the source and receiver are aligned along the z-axis
ab = 66

#EM-Frequencies Generated by Source 
# freq = np.logspace(1, 5, 5).astype(int)
freq = np.array([   383,   1820,   8488,  40840, 133530])
freq_dim = freq.shape[0]
fem_dim = 2*freq.shape[0] + 1

xdirect = None

#fx is the array of the position of the receivers along x-axis
src_x = [0, 0, 0, 0, 0]
rec_x = np.array([7.93, 7.95, 7.93, 7.92, 7.97])
rec_n = rec_x.shape[0]

#fx is the array of the position of the receivers along y-axis
src_y = [0]
rec_y = [0]

dim_0 = s_rmd_rho_in.shape[1]
# N = int(2*dim_0)
N = int(1e4)

#Creating an index list to shuffle the data
int_list = np.linspace(0, dim_0 -1, dim_0).astype(int)
# int_list = np.append(int_list, int_list)
int_list = np.random.choice(int_list, size = N, replace = True).astype(int)

fEM_arr = np.zeros([N, fem_dim])
rho_arr = np.zeros([N, rho_dim])
fEM_arr_temp = np.zeros(fem_dim)

noise_fr = 0 #add noise to Primary FDEM Data

#Height distribution parameters
h_dist = 'unif'

#Normal distribution parameters
h_loc = -3
h_scale = 10

h_param = [h_dist, h_loc, h_scale]

#Uniform distribution parameters
low_v = -80
high_v = -3

#Model type: mod_type = 'dipole' => FDEM signal is in unit A/m
# else: ratio of secondary to primary
mod_type = 'ratio'

save_data = False

start = time.time()

if noise_fr == 0:
    for i in range(0, N):
        for j in range(0, rec_n):
            
            src_x_temp = np.array([src_x[j]])
            rec_x_temp = np.array([rec_x[j]])
            
            rho_idx = int_list[i]
            s_rmd_rho_temp = s_rmd_rho[:, rho_idx]
            
            if h_dist == 'normal':
                height = np.round(np.random.normal(loc = h_loc, scale = h_scale, size = 1), decimals = 3)
                
            if h_dist == 'unif':
                height =  np.round(np.random.uniform(low = low_v, high = high_v, size = 1), decimals = 3)
                
            else: 
                height = [h_loc]
            
            fEM_arr_temp[0] = height[0]
            
            freq_temp = np.array([freq[j]])
            
            inp_data = {
                'src': [src_x_temp, src_y, height], 
                'rec': [rec_x_temp, rec_y, height], 
                'depth': depth,
                'freqtime': freq_temp, 
                'ab': ab, 
                'xdirect': xdirect,
                'htarg': {'pts_per_dec': -1}, 
                'verb': verb
            }
            
            
            fEM_arr_temp[2*j +1: 2*j+3] = sim_empymod_data( s_rmd_rho_temp, inp_data, fEM_save_path, mod_type, save_data )
            
            
            
        fEM_arr[i,:] = fEM_arr_temp[:]
        rho_arr[i,:] = s_rmd_rho_temp[:]


# if noise_fr == 1:
#     freq_arr = np.zeros([N, freq_dim])
#     for i in range(0, N):
#         rho_idx = int_list[i]
#         s_rmd_rho_temp = s_rmd_rho[:, rho_idx]
#         freq_st = freq + np.multiply(0.25*freq, np.random.normal(loc = 0,scale = 1, size = freq_dim))
#         height = np.round(np.random.normal(loc = h_loc, scale = h_scale, size = 1), decimals = 2)
#         # height = [-1*heights[i]]
        
#         fEM_arr_temp = sim_empymod_data( s_rmd_rho_temp, depth, verb, ab, freq_st, xdirect,
#                               fx, fy, height, fEM_save_path, save_data = False)
#         fEM_arr[i,:] = fEM_arr_temp
#         rho_arr[i,:] = s_rmd_rho_temp
#         freq_arr[i,:] = freq_st
#     np.save(freq_save_path, freq_arr)
    
end = time.time()


# sim_dict = {'fx': fx, 'fy': fy, 'freq': freq, 'depth_factor': depth_fac,
#             'rho_factor': rho_fac, 'height_dist_param': h_param}


print('Time to simulate', N,'profiles', end - start, '[s]')
np.save(fEM_save_path, fEM_arr)
# np.save(sim_dict_path, sim_dict)
np.save(rho_save_path, rho_arr)

#unit test
rho_test = np.load(rho_save_path)
if rho_test.any() !=rho_arr.any():
    print('Unit test failed')



